apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  labels:
    app: udagram-reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: udagram-reverseproxy
