version: 2.1
orbs:
  docker: circleci/docker@1.5.0
  node: circleci/node@4.2.0
executors:
  docker-publisher:
  environment:
    -image: circleci/node:14.16.0
  auth:
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_PASSWORD
jobs:
  publishLatestToHub:
  executor: docker-publisher
  steps:
    - checkout
    - setup_remote_docker
    - run:
      name: Publish Docker Image to Docker Hub
      command: echo “$DOCKERHUB_PASSWORD” | docker login -u “$DOCKERHUB_USERNAME” — password-stdin
      docker build -t udagram-api-feed ./udagram-api-feed
      docker build -t udagram-api-user ./udagram-api-user
      docker build -t udagram-frontend ./udagram-frontend

      docker tag udagram-api-feed jlord31/udagram-api-feed:v1
      docker tag udagram-api-user jlord31/udagram-api-user:v1
      docker tag udagram-frontend jlord31/udagram-frontend:v1

      docker push jlord31/udagram-api-feed:v1
      docker push jlord31/udagram-api-user:v1
      docker push jlord31/udagram-frontend:v1
workflows:
  version: 2
  build-master:
  jobs:
    -publishLatestToHub
